@startuml
left to right direction
skinparam packageStyle rectangle
title Select Fulfillment
actor "AI Agent" as Client
actor "eStore Backend" as Backend
rectangle "UCP Server" {
    usecase "Update Checkout Session" as UC1
    usecase "Select Fulfillment" as UC2
}
Client --> UC1: "1. Request Checkout update"
note on link
  - method (배송 방법)
    - destinations (배송지)
    - groups (배송 그룹)
      - options(배송 옵션 : standard, express)
end note
UC2 .> UC1 : <<extend>>
UC1 --> Backend: "2. Calculate shipping & Validate"
@enduml