@startuml
left to right direction
skinparam packageStyle rectangle

title Discovery

actor "AI Agent" as Client
rectangle "UCP Server" {
    usecase "Get Business Capabilities" as UC1
}
Client --> UC1: "Request Business Capabilities"

@enduml